format = """
$python\
$aws\
$kubernetes\
$git_branch$git_commit$git_state$git_status\
$directory\
$line_break\
$status$character
"""

[aws]
format = "[\\[$symbol$profile\\]]($style)"
style = "bold blue"

[aws.region_aliases]
us-east-1 = "ue1"

[directory]
format = ":: ([ $read_only]($read_only_style) )[$path]($style)"
truncation_length = 4
truncate_to_repo = true
fish_style_pwd_dir_length = 2

[directory.substitutions]
"Project-Vitamin" = "PV"

[git_branch]
format = "( :: [$symbol$branch]($style))"
only_attached = false

[git_commit]
only_detached = true
tag_disabled = false

[git_state]

[git_status]
format = "([ \\[$all_status$ahead_behind\\]]($style) )"

[kubernetes]
format = "([\\[$symbol$context\\]]($style))"
style = "blue bold"
symbol = "❄ "
disabled = false

[python]
detect_extensions = []
format = "[\\[${symbol}${version}\\]]($style)"
pyenv_version_name = true

[status]
disabled = false
